import React from 'react';
import {hydrateRoot,createRoot} from 'react-dom/client';
import App from './App';
import {config} from './config';
import './archive/archive.css';
document.documentElement.style.setProperty('--green',config.accent);
const initial=document.getElementById('initial-portfolio');
const root=document.getElementById('root');
const app=<App pathname={location.pathname} initialPieces={initial?JSON.parse(initial.textContent):config.workPlaceholders}/>;
if(root.hasChildNodes())hydrateRoot(root,app);else createRoot(root).render(app);
