const collection=document.querySelector('[data-collection]');
const studio=document.querySelector('#studio-tools');
let pieces=[],filter='all',currentPiece=0;
const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;};
async function api(url,options){const response=await fetch(url,options);let result;try{result=await response.json();}catch{throw Error('Could not connect. Please try again.');}if(!response.ok)throw Error(result.message||'Please try again.');return result;}
function media(piece,controls=false){const node=el(piece.kind==='video'?'video':'img');node.src=piece.src;if(piece.kind==='photo'){node.alt=piece.alt;node.loading='lazy';}else{node.controls=controls;node.preload='metadata';node.playsInline=true;node.setAttribute('aria-label',piece.title);if(piece.captions){const track=el('track');track.kind='captions';track.label='English';track.srclang='en';track.src=piece.captions;node.append(track);}}return node;}
let viewer;
function openPiece(index){currentPiece=index;if(!viewer){viewer=el('dialog',null,'work-viewer');document.body.append(viewer);viewer.addEventListener('close',()=>{viewer.querySelector('video')?.pause();});}viewer.replaceChildren();const p=pieces[index];const close=el('button','Close ×','viewer-close');close.onclick=()=>viewer.close();const heading=el('h2',p.title);heading.id='viewer-title';viewer.setAttribute('aria-labelledby','viewer-title');viewer.append(close,media(p,true),heading,el('p',p.description,'piece-description'));const navigation=el('div',null,'viewer-nav');for(const [label,step] of [['← Previous',-1],['Next →',1]]){const button=el('button',label);button.onclick=()=>{viewer.querySelector('video')?.pause();openPiece((currentPiece+step+pieces.length)%pieces.length);};navigation.append(button);}viewer.append(navigation);if(!viewer.open)viewer.showModal();close.focus();}
function renderCollection(){collection.replaceChildren();const shown=pieces.filter(p=>filter==='all'||p.kind===filter);if(!shown.length){const empty=el('div',null,'collection-empty');const prop=el('img');prop.src='/props/content-v2.png';prop.alt='';prop.width=500;prop.height=500;empty.append(prop,el('h3',pieces.length?'Nothing in this drawer yet.':'The collection is on its way.'),el('p',pieces.length?'Try another format.':'New work will appear here soon.'));collection.append(empty);return;}shown.forEach((p,i)=>{const card=el('button',null,'work-card');card.style.setProperty('--tilt',[-3,2,-1,3][i%4]+'deg');card.append(media(p),el('span',p.kind==='video'?'Film · Play ↗':'Photography · Open ↗','piece-kind'),el('h3',p.title));card.onclick=()=>openPiece(pieces.indexOf(p));collection.append(card);});}
if(collection){api('/api/portfolio').then(({items})=>{pieces=collection.dataset.collection==='featured'?items.filter(p=>p.featured).slice(0,3):items;if(collection.dataset.collection==='featured'&&!pieces.length)pieces=items.slice(0,3);renderCollection();}).catch(error=>{collection.replaceChildren(el('p',error.message));});document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderCollection();});}
function field(form,label,name,value,type='input'){const wrap=el('label',label);const input=el(type);input.name=name;input.value=value;wrap.append(input);form.append(wrap);return input;}
async function loadStudio(){const {items}=await api('/api/portfolio?all=1');const list=document.querySelector('#studio-list');list.replaceChildren();if(!items.length)list.append(el('p','Your first piece starts above. Drafts stay private until you publish them.'));for(const p of items){const form=el('form',null,'studio-edit');form.append(media(p,true));const title=field(form,'Title','title',p.title);title.required=true;title.maxLength=120;const description=field(form,'Description / transcript','description',p.description,'textarea');description.maxLength=2500;const alt=field(form,'Photo description','alt',p.alt);alt.maxLength=500;const order=field(form,'Display order (lowest first)','order',p.order);order.type='number';order.min=-10000;order.max=10000;const status=field(form,'Visibility','status','','select');for(const value of ['draft','published','archived']){const option=el('option',value[0].toUpperCase()+value.slice(1));option.value=value;status.append(option);}status.value=p.status;const feature=field(form,'Feature on homepage','featured','');feature.type='checkbox';feature.checked=p.featured;const save=el('button','Save changes','button');const note=el('p');note.setAttribute('role','status');form.append(save,note);form.onsubmit=async event=>{event.preventDefault();save.disabled=true;note.textContent='Saving…';try{await api('/api/portfolio/'+p.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.value,description:description.value,alt:alt.value,order:Number(order.value),status:status.value,featured:feature.checked})});note.textContent='Saved. '+(status.value==='published'?'This piece is live.':'This piece is private.');}catch(error){note.textContent=error.message;}finally{save.disabled=false;}};list.append(form);}}
if(collection||studio)api('/api/portfolio/session').then(async session=>{document.querySelectorAll('.owner-link').forEach(n=>n.hidden=!session.canManage);if(!studio)return;const access=document.querySelector('#studio-access');if(!session.canManage){access.textContent='This studio is reserved for the site owner. Open this site while signed in to your owner account.';return;}access.textContent='Owner access · drafts are private';studio.hidden=false;await loadStudio();}).catch(error=>{if(studio)document.querySelector('#studio-access').textContent=error.message;});
document.querySelector('#upload-work')?.addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,status=form.querySelector('.upload-status'),button=form.querySelector('button');const data=new FormData(form);const file=data.get('file');if(file.size>20*1024*1024){status.textContent='Please use a file under 20 MB.';return;}button.disabled=true;status.textContent='Uploading your draft…';try{await api('/api/portfolio',{method:'POST',body:data});form.reset();status.textContent='Draft saved. Set its visibility to Published below when it’s ready.';await loadStudio();}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
