import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import {DatabaseSync} from 'node:sqlite';
import {createWorker,CONSENT_VERSION} from '../worker/app.js';
import {sqliteBinding} from '../worker/local-db.js';
async function setup(){const db=new DatabaseSync(':memory:');for(const name of (await fs.readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())db.exec(await fs.readFile('drizzle/'+name,'utf8'));return {db,env:{DB:sqliteBinding(db)},app:createWorker({'/index.html':{type:'text/html',body:btoa('Home')},'/privacy/index.html':{type:'text/html',body:btoa('Privacy')},'/404.html':{type:'text/html',body:btoa('Not found')}})};}
const payload=()=>({id:crypto.randomUUID(),email:'test@example.invalid',message:'Synthetic local test only.',consent:true});
const request=(data,headers={})=>new Request('https://example.test/api/contact',{method:'POST',headers:{Origin:'https://example.test','Content-Type':'application/json',...headers},body:JSON.stringify(data)});
test('consent required; minimal data; retry and conflict handling',async()=>{const {db,app,env}=await setup();const data=payload();assert.equal((await app.fetch(request({...data,consent:false}),env)).status,422);assert.equal(db.prepare('SELECT COUNT(*) n FROM inquiries').get().n,0);assert.equal((await app.fetch(request({...data,ip:'not stored'}),env)).status,201);assert.equal((await app.fetch(request(data),env)).status,200);assert.equal((await app.fetch(request({...data,message:'Different message content'}),env)).status,409);const row=db.prepare('SELECT * FROM inquiries').get();assert.equal(row.consent_version,CONSENT_VERSION);assert.equal(row.name,null);assert.equal(row.expires_at-row.received_at,90*86400000);assert.equal(Object.keys(row).length,7);db.close();});
test('cross-origin, invalid, oversized and bot requests rejected',async()=>{const {db,app,env}=await setup();assert.equal((await app.fetch(request(payload(),{Origin:'https://other.test'}),env)).status,403);assert.equal((await app.fetch(request(payload(),{'Content-Type':'text/plain'}),env)).status,415);assert.equal((await app.fetch(request({...payload(),message:'x'.repeat(17000)}),env)).status,413);assert.equal((await app.fetch(request({...payload(),website:'spam'}),env)).status,400);assert.equal((await app.fetch(request({...payload(),email:'bad'}),env)).status,422);assert.equal(db.prepare('SELECT COUNT(*) n FROM inquiries').get().n,0);db.close();});
test('rate limits and truthful unavailable response',async()=>{const {db,app,env}=await setup();for(let i=0;i<3;i++)assert.equal((await app.fetch(request(payload()),env)).status,201);assert.equal((await app.fetch(request(payload()),env)).status,429);assert.equal((await createWorker({}).fetch(request(payload()),{})).status,503);db.close();});
test('retention, policy routes, missing pages, security headers',async()=>{const {db,app,env}=await setup();db.prepare('INSERT INTO inquiries VALUES (?,?,?,?,?,?,?)').run('old',null,'old@example.invalid','Old synthetic data',0,1,'old');const home=await app.fetch(new Request('https://example.test/'),env);assert.equal(home.status,200);assert.equal(db.prepare('SELECT COUNT(*) n FROM inquiries').get().n,0);assert.equal(home.headers.get('X-Content-Type-Options'),'nosniff');assert.ok(home.headers.get('Content-Security-Policy').includes("frame-src 'none'"));assert.equal((await app.fetch(new Request('https://example.test/privacy'),env)).status,308);assert.equal((await app.fetch(new Request('https://example.test/privacy/'),env)).status,200);assert.equal((await app.fetch(new Request('https://example.test/missing'),env)).status,404);assert.equal((await app.fetch(new Request('https://example.test/api/contact'),env)).status,405);db.close();});
