import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs/promises';
import {sqliteBinding} from '../worker/local-db.js';
import {portfolioRoute} from '../worker/portfolio.js';
async function setup(){const db=new DatabaseSync(':memory:');for(const file of (await fs.readdir('drizzle')).filter(n=>n.endsWith('.sql')).sort())db.exec(await fs.readFile('drizzle/'+file,'utf8'));const files=new Map();return {db,env:{DB:sqliteBinding(db),PORTFOLIO_OWNER_EMAIL:'owner@example.test',BUCKET:{async put(k,v){files.set(k,v);},async delete(k){files.delete(k);},async get(k){const body=files.get(k);return body?{body,size:body.length}:null;}}}};}
function req(path,method='GET',body,owner=false,origin='https://example.test'){return new Request('https://example.test'+path,{method,body,headers:{Origin:origin,...(owner?{'oai-authenticated-user-id':'owner-id','oai-authenticated-user-email':'owner@example.test'}:{})}});}
function upload(kind='photo',speech='no'){const form=new FormData();form.set('title','Synthetic test piece');form.set('alt','Synthetic test image');form.set('description','Test description');form.set('hasSpeech',speech);form.set('file',new Blob([kind==='photo'?new Uint8Array([255,216,255,1]):new Uint8Array([0,0,0,16,102,116,121,112,105,115,111,109])]),kind==='photo'?'test.jpg':'test.mp4');return form;}
test('owner-only writes, private drafts, publication, archive, and persisted metadata',async()=>{const {db,env}=await setup();assert.equal((await portfolioRoute(req('/api/portfolio','POST',upload()),env)).status,403);assert.equal((await portfolioRoute(req('/api/portfolio?all=1'),env)).status,403);assert.equal((await portfolioRoute(req('/api/portfolio','POST',upload(),true,'https://foreign.test'),env)).status,403);const saved=await portfolioRoute(req('/api/portfolio','POST',upload(),true),env);assert.equal(saved.status,201);const {item}=await saved.json();assert.equal(item.status,'draft');assert.equal((await portfolioRoute(req(item.src),env)).status,404);assert.equal((await portfolioRoute(req(item.src,'GET',undefined,true),env)).status,200);assert.equal((await (await portfolioRoute(req('/api/portfolio'),env)).json()).items.length,0);const patch={title:item.title,description:item.description,alt:item.alt,status:'published',featured:true,order:2};assert.equal((await portfolioRoute(req('/api/portfolio/'+item.id,'PATCH',JSON.stringify(patch),true),env)).status,200);assert.equal((await portfolioRoute(req(item.src),env)).status,200);assert.equal((await (await portfolioRoute(req('/api/portfolio'),env)).json()).items[0].featured,true);patch.status='archived';await portfolioRoute(req('/api/portfolio/'+item.id,'PATCH',JSON.stringify(patch),true),env);assert.equal((await portfolioRoute(req(item.src),env)).status,404);assert.equal(db.prepare('SELECT status FROM portfolio').get().status,'archived');db.close();});
test('file type, alt text and speech captions validated',async()=>{const {db,env}=await setup();const bad=upload();bad.set('file',new Blob(['<script>alert(1)</script>']),'test.jpg');assert.equal((await portfolioRoute(req('/api/portfolio','POST',bad,true),env)).status,415);const noAlt=upload();noAlt.set('alt','');assert.equal((await portfolioRoute(req('/api/portfolio','POST',noAlt,true),env)).status,422);assert.equal((await portfolioRoute(req('/api/portfolio','POST',upload('video','yes'),true),env)).status,422);assert.equal(db.prepare('SELECT COUNT(*) n FROM portfolio').get().n,0);db.close();});
