import React,{useLayoutEffect,useRef} from 'react';import {gsap} from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';
import Footer from './Footer';import Work from './Work';import Contact from './Contact';import {config} from '../config';
gsap.registerPlugin(ScrollTrigger);
export default function Chapters({paused,pieces,collectionError,onNavigate}){const root=useRef();
 useLayoutEffect(()=>{if(paused)return;const ctx=gsap.context(()=>{gsap.utils.toArray('.reveal').forEach(el=>gsap.from(el,{y:36,opacity:0,duration:.8,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 92%',once:true}}));gsap.from('.approach-image',{scale:1.12,ease:'none',scrollTrigger:{trigger:'.approach',start:'top bottom',end:'bottom top',scrub:true}});},root);return()=>ctx.revert();},[paused]);
 return <div ref={root}><Work paused={paused} pieces={pieces} collectionError={collectionError}/>
 <section className="capabilities" id="capabilities" tabIndex="-1"><div className="section-intro reveal"><h2>From “what if”<br/>to out there.</h2><p>A creative team beside you for the thinking,<br/>the making and the getting it seen.</p></div><div className="service-list">{config.services.map((s,i)=><details className="service" key={s.title} open={i===0}><summary><span className="service-name">{s.title}</span><span className="service-toggle" aria-hidden="true">+</span></summary><div className="service-content"><p>{s.body}</p><ul>{s.deliverables.map(d=><li key={d}>{d}</li>)}</ul></div></details>)}</div></section>
 <section className="approach" id="approach" tabIndex="-1"><div className="approach-art"><img className="approach-image" src="/identity/studio.webp" width="1672" height="941" alt="Monochrome contact sheets, a camera lens and translucent acetate arranged on a studio table." loading="lazy"/><h2>Made<br/>beside you.</h2></div><div className="approach-notes">{config.strengths.map(s=><div className="approach-note reveal" key={s.title}><h3>{s.title}</h3><p>{s.body}</p></div>)}<a className="line-link" href="/approach/">Get to know our approach <span aria-hidden="true"></span></a></div></section>
 <Contact/><Footer/></div>;
}
