import React,{useState,useRef} from 'react';import {config} from '../config';

export default function Contact({standalone=false}){const [mode,setMode]=useState('call'),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const id=useRef(crypto.randomUUID());

 async function submit(e){e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;setBusy(true);setStatus('Sending…');const data=new FormData(form);const message=(mode==='call'?'Call request\n':'Project inquiry\n')+data.get('message');

 try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:id.current,name:data.get('name'),email:data.get('email'),message,website:data.get('website'),consent:data.get('consent')==='on'})});const result=await r.json();if(!r.ok)throw Error(result.message||'Please try again.');form.reset();id.current=crypto.randomUUID();setStatus(mode==='call'?'Your call request is saved for our team to review. A time has not been booked yet.':'Your inquiry is saved for our team to review. Thank you.');}catch(error){setStatus(error.message==='Failed to fetch'?'Could not connect. Your message is still here; try again or email our team.':error.message);}finally{setBusy(false);}}

 return <section id="contact" className={"contact "+(standalone?"contact-standalone":"")} tabIndex="-1"><div className="contact-intro">{standalone?<h1>Hello is<br/>a good start.</h1>:<h2>Let’s make<br/>something<br/>you love.</h2>}<p>Tell us where you are and what you have in mind.<br/>We’ll find the next step together.</p>{config.bookingUrl&&<a className="direct-booking" href={config.bookingUrl}>Book a call </a>}<a className="contact-email" href={'mailto:'+config.email}>{config.email}</a></div><div className="contact-details"><div className="contact-choice" role="group" aria-label="Inquiry type"><button type="button" aria-pressed={mode==='call'} disabled={busy} onClick={()=>{setMode('call');setStatus('');}}>Request a call</button><button type="button" aria-pressed={mode==='project'} disabled={busy} onClick={()=>{setMode('project');setStatus('');}}>Send a brief</button></div><form className="contact-form" onSubmit={submit}><label>Name (optional)<input name="name" maxLength="100" autoComplete="name" placeholder="Your name"/></label><label>Email *<input name="email" type="email" required maxLength="254" autoComplete="email" placeholder="you@company.com"/></label><label>{mode==='call'?'What would you like to talk about? *':'Tell us about your project *'}<textarea name="message" required minLength="10" maxLength="2400" rows="4" placeholder={mode==='call'?'A little about your project. You can include a good time to talk.':'The idea, the audience, the ambition.'} aria-describedby="message-help"/></label><p id="message-help" className="form-help">{mode==='call'?'This sends a request; a call time will need to be agreed. ':'Please leave out sensitive information. '}10–2,400 characters.</p><div className="honeypot" aria-hidden="true"><label>Leave empty<input name="website" tabIndex="-1" autoComplete="off"/></label></div><label className="consent"><input type="checkbox" name="consent" required/><span>I agree to my details being used to respond to this inquiry, as explained in the <a href="/privacy/">Privacy Policy</a>. This does not sign me up for marketing.</span></label><button type="submit" disabled={busy}>{busy?'Sending…':mode==='call'?'Request a call':'Send your brief'}<span aria-hidden="true"></span></button><p role="status" className="form-status">{status}</p></form></div></section>;

}

