import React,{useLayoutEffect,useRef} from 'react';import {gsap} from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';
gsap.registerPlugin(ScrollTrigger);
const endings=['worth sharing.','one of a kind.','just beginning.','made to connect.','ready to be seen.'];
export default function Hero({paused,ready=true}){const root=useRef();
 useLayoutEffect(()=>{if(paused||!ready)return;let rotation;const ctx=gsap.context(()=>{const words=gsap.utils.toArray('.story-ending');const letters=words.map(word=>[...word.querySelectorAll('.story-char')]);gsap.set(letters.flat(),{y:0,yPercent:120,rotation:12});gsap.set(letters[0],{yPercent:0,rotation:0});rotation=gsap.timeline({repeat:-1});letters.forEach((chars,i)=>{const next=letters[(i+1)%letters.length];const at=i*5.05+3;rotation.to(chars,{yPercent:-125,rotation:-10,duration:.55,stagger:{amount:.42},ease:'power2.in'},at).fromTo(next,{y:0,yPercent:120,rotation:12},{yPercent:0,rotation:0,duration:.68,stagger:{amount:.4},ease:'power3.out',immediateRender:false},at+.95);});},root);const observer=new IntersectionObserver(([entry])=>{if(entry.isIntersecting)rotation?.resume();else rotation?.pause();},{threshold:.05});observer.observe(root.current.querySelector('.opening-copy'));return()=>{observer.disconnect();ctx.revert();};},[paused,ready]);
 useLayoutEffect(()=>{if(paused||!ready)return;const mm=gsap.matchMedia();const ctx=gsap.context(()=>{gsap.from('.opening-line>span',{yPercent:105,stagger:.12,duration:1,ease:'power3.out'});gsap.from('.opening-summary',{y:20,opacity:0,duration:.8,delay:.35});},root);
 mm.add('(min-width:768px)',()=>{const local=gsap.context(()=>{const stage=root.current.querySelector('.flow-stage');const tl=gsap.timeline({scrollTrigger:{trigger:root.current,start:'top top',end:'bottom bottom',scrub:1,invalidateOnRefresh:true}});tl.to('.opening-copy',{y:-80,opacity:0,duration:.25},0).to('.hero-visual',{x:()=>stage.clientWidth*.105,y:()=>stage.clientHeight*.26,scale:.39,duration:.7,ease:'power2.inOut'},.08).to('.hero-visual img',{scale:1.35,xPercent:-10,duration:.7,ease:'power2.inOut'},.08).from('.welcome-copy',{y:65,opacity:0,duration:.35},.5);},root);return()=>local.revert();});return()=>{ctx.revert();mm.revert();};},[paused,ready]);
 return <section id="top" className="flow-hero" ref={root} tabIndex="-1"><div className="flow-stage"><div className="hero-visual"><img src="/identity/creative-hands.webp" width="1672" height="941" fetchPriority="high" alt="Hands studying photographic contact sheets beside a camera, in a monochrome creative studio."/></div><div className="opening-copy"><h1 aria-label="Your story is worth sharing."><span className="opening-line" aria-hidden="true"><span>Your story is</span></span><span className="rotating-line" aria-hidden="true">{endings.map((ending,i)=><span className={"story-ending "+(i===0?"is-first":"")} key={ending}>{[...ending].map((char,j)=><span className={"story-char"+(char==='.'?' hero-period':'')} key={j}>{char===' '?'\u00a0':char}</span>)}</span>)}</span></h1><div className="opening-summary"><p>The creative marketing agency<br/> working beside you on content,<br/> social and campaigns that feel like you.</p></div></div><div className="welcome-copy"><h2>Your vision.<br/>Our craft.<br/>Made together.</h2><p>You know your business. We bring a fresh creative perspective. Together, we shape the idea, make the content and keep your voice at the heart of it.</p><a className="line-link" href="/capabilities/">Find your starting point</a></div></div></section>;
}
