import React,{useEffect,useRef,useState} from 'react';import {gsap} from 'gsap';import {ScrollTrigger} from 'gsap/ScrollTrigger';import {config} from '../config';import Work from './Work';import Contact from './Contact';import Footer from './Footer';import PageMotion from './PageMotion';
gsap.registerPlugin(ScrollTrigger);
function PageHeading({lines,children,className=''}){return <header className={'page-hero '+className}><h1>{lines.map(line=><span className="word-wrap" key={line}><span>{line}</span></span>)}</h1>{children}</header>;}
function Invitation({title='Something on your mind?',body='You don’t need a finished brief. Bring us the idea, the question or the thing you’re still figuring out.'}){return <section className="page-invitation" data-arrive><h2>{title}</h2><div><p>{body}</p><a className="solid-link" href="/contact/">Let’s talk it through</a></div></section>;}
export function PortfolioPage({paused,pieces,collectionError}){const root=useRef();const [filter,setFilter]=useState('all'),[owner,setOwner]=useState(false);
 useEffect(()=>{const a=new AbortController();fetch('/api/portfolio/session',{signal:a.signal}).then(r=>r.json()).then(d=>setOwner(!!d.canManage)).catch(()=>{});return()=>a.abort();},[]);
 const shown=pieces.filter(p=>filter==='all'||(p.placeholder?(filter==='video'?p.id==='videography':p.id==='photography'):p.kind===filter));
 return <div ref={root} className="destination portfolio-destination"><PageMotion root={root} paused={paused}/><PageHeading lines={['Take a','closer look.']}><div className="page-lead"><p>Stories in motion. Moments worth keeping.<br/>A home for what we make together.</p><a className="line-link" href="/contact/">Have something in mind?</a></div><div className="portfolio-tabs" aria-label="Filter portfolio">{[['all','Everything'],['photo','Photography'],['video','Videography']].map(([id,title])=><button key={id} aria-pressed={filter===id} onClick={()=>setFilter(id)}>{title}</button>)}{owner&&<a className="owner-upload" href="/studio/">Add your media</a>}</div></PageHeading><div aria-live="polite" className="sr-only">{shown.length} {shown.length===1?'piece':'pieces'} shown</div>{shown.length?<Work paused={paused} pieces={shown} collectionError={collectionError} fullPage/>:<div className="collection-empty-state"><h2>More to come.</h2><p>There’s nothing in this part of the collection just yet.</p></div>}<Invitation title="Let’s make your next favourite."/><Footer/></div>;
}
const serviceDetails=[
 {heading:'Content with a little character.',intro:'There’s a story in what you do. We’ll help you find it, capture it and share it in a way that feels like your brand.',outputs:[['Videography','Brand stories, product features and short-form videos, planned around the places they’ll be seen.'],['Photography','Thoughtful images of your people, products and spaces, with a consistent point of view.'],['Editing & cutdowns','Pacing, sound, captions and alternate formats that make the most of what we capture.']]},
 {heading:'A familiar face in the feed.',intro:'Social works best when it sounds like someone, not everyone. Together, we’ll build a recognisable voice and a plan you can keep coming back to.',outputs:[['Content planning','Themes, formats and a useful publishing direction shaped around your audience.'],['Social creative','Images, videos and copy that belong together without making every post look the same.'],['Campaign assets','A connected set of pieces to support a launch, an offer or a moment worth sharing.']]},
 {heading:'Find the thread. Follow it.',intro:'Before we make anything, we get curious. What makes your brand yours? Who are you here for? What do you want people to remember?',outputs:[['Creative direction','A shared visual and verbal direction to guide the work.'],['Brand messaging','Clear language for what you do, why it matters and what makes it different.'],['Campaign concepts','Ideas grounded in your audience, your objectives and what you can bring to life.']]},
 {heading:'Let’s put it out into the world.',intro:'A good idea needs a good release. We help connect the pieces, plan where they go and learn from the response.',outputs:[['Channel planning','Choose the right places and formats for the message.'],['Paid media creative','Creative assets developed around the campaign brief and the needs of each placement.'],['Campaign review','Make room to reflect, understand the response and decide what to try next.']]}
];
export function CapabilitiesPage({paused}){const root=useRef();return <div ref={root} className="destination capabilities-destination"><PageMotion root={root} paused={paused}/><PageHeading lines={['Your ideas.','Our shared craft.']}><div className="page-lead"><p>Content, social, strategy and campaigns.<br/>Come with a clear plan or a curious “what if.”<br/>We’ll find a starting point together.</p></div><nav className="service-directory" aria-label="Explore services">{config.services.map((s,i)=><a key={s.title} href={'#service-'+i}>{s.title.replace('.','')}</a>)}</nav></PageHeading><div className="service-chapters">{serviceDetails.map((s,i)=><section key={s.heading} id={'service-'+i} className={'service-chapter service-chapter-'+i} tabIndex="-1"><div className="service-title"><span className="large-service-word" data-drift>{config.services[i].title}</span></div><div className="service-story"><h2 data-arrive>{s.heading}</h2><p data-arrive>{s.intro}</p><div className="service-outputs">{s.outputs.map(([title,body])=><div data-arrive key={title}><h3>{title}</h3><p>{body}</p></div>)}</div></div></section>)}</div><Invitation title="One piece or the whole picture." body="Some projects need a fresh set of eyes. Others need a creative partner from the first idea to the final edit. Tell us where you are."/><Footer/></div>;}
const steps=[
 {title:'First, we listen.',body:'Tell us what you’re building, what feels right and what’s been getting in the way. We’ll ask questions and get to know the people you want to reach.',detail:'A conversation about your brand, your audience and what you’d like to make.'},
 {title:'Find a direction.',body:'We turn that conversation into a creative direction. You’ll have a chance to react, ask questions and help shape it before production begins.',detail:'A shared brief, a clear scope and a direction everyone understands.'},
 {title:'Make it together.',body:'The idea becomes content. We plan, capture and edit with the final use in mind, keeping the creative connected as it moves between formats.',detail:'Production and editing, with agreed checkpoints along the way.'},
 {title:'Make the details count.',body:'We review the work together and refine the pieces. This is where the pacing, the wording and the small things get the attention they deserve.',detail:'Focused feedback and revisions within the agreed project scope.'},
 {title:'Share it. Learn from it.',body:'The work is ready to meet its audience. We help you think through the release and, where it’s part of the project, use the response to inform what comes next.',detail:'Final assets, a walkthrough together and room for the next conversation.'}
];
export function ApproachPage({paused}){const root=useRef();const [active,setActive]=useState(0);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)setActive(Number(e.target.dataset.step));}),{rootMargin:'-30% 0px -35% 0px'});root.current.querySelectorAll('[data-step]').forEach(el=>observer.observe(el));return()=>observer.disconnect();},[]);
 return <div ref={root} className="destination approach-destination"><PageMotion root={root} paused={paused}/><PageHeading className="approach-page-hero" lines={['Pull up','a chair.']}><div className="approach-window"><img src="/identity/studio.webp" alt="Photographic contact sheets and a camera lens laid out on a creative worktable." width="1672" height="941" data-drift/></div><p className="approach-welcome">A place beside you, from the first conversation.<br/>Here’s how we turn a shared direction into work.</p></PageHeading><section className="process-journey" aria-label="How we work"><nav className="process-guide" aria-label="Project stages"><p>From hello<br/>to out there.</p>{steps.map((s,i)=><a key={s.title} href={'#step-'+i} aria-current={active===i?'step':undefined}><span>0{i+1}</span><span>{s.title}</span></a>)}</nav><div className="process-stages">{steps.map((s,i)=><section className="process-stage" data-step={i} id={'step-'+i} key={s.title} tabIndex="-1"><span className="process-number" aria-hidden="true">0{i+1}</span><h2 data-arrive>{s.title}</h2><p data-arrive>{s.body}</p><p className="process-detail" data-arrive>{s.detail}</p></section>)}</div></section><section className="working-promise"><h2 data-arrive>Your team.<br/>With us beside it.</h2><div>{config.strengths.map(s=><article data-arrive key={s.title}><h3>{s.title}</h3><p>{s.body}</p></article>)}</div></section><Invitation title="You don’t have to have it all figured out."/><Footer/></div>;
}
export function ContactPage({paused}){const root=useRef();return <div ref={root} className="destination contact-destination"><PageMotion root={root} paused={paused}/><Contact standalone/><section className="contact-faq"><h2 data-arrive>A few things<br/>you might be wondering.</h2><div>{[
 ['Do we need a finished brief?','Not at all. A little context about your business and what you’re hoping to do is a great place to start. We can work through the rest together.'],
 ['Can we start with one project?','Yes. We can discuss a single piece of content, a campaign or a broader creative partnership. The scope and terms are agreed before work begins.'],
 ['Is this a confirmed booking?','The form sends a call request. A time still needs to be agreed; it does not book a calendar appointment. You can also email us directly.'],
 ['Where are you based?','Made Beside is based in Ontario, Canada. Tell us where your project is happening so we can discuss what’s practical.'],
 ['What about budgets and timing?','Share any budget range or important dates in your note if you have them. We’ll discuss the scope, costs and schedule before committing to the project.']
 ].map(([q,a])=><details key={q} data-arrive><summary>{q}<span aria-hidden="true">+</span></summary><p>{a}</p></details>)}</div></section><Footer/></div>;}
