import React,{useRef,useState} from 'react';
const links=[['/','Home'],['/portfolio/','Our work'],['/capabilities/','What we do'],['/approach/','Our approach'],['/contact/','Say hello']];
export function MenuIcon({index}){return <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{index===0?<><path d="m4 10 8-6 8 6v10H4Z"/><path d="M10 20v-6h4v6"/></>:index===1?<><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m10 9 5 3-5 3Z"/></>:index===2?<><path d="M4 6h16M4 12h12M4 18h16"/><circle cx="19" cy="12" r="1"/></>:index===3?<><circle cx="8" cy="9" r="4"/><circle cx="16" cy="15" r="4"/></>:<><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 6 9 7 9-7"/></>}</svg>}
export default function SiteNav(){const [open,setOpen]=useState(false),[pinned,setPinned]=useState(false);const root=useRef(),toggle=useRef();
 const close=()=>{setOpen(false);setPinned(false);};
 return <><header className="site-header"><a className="brand" href="/" aria-label="Made Beside home"><span className="made-wordmark"><img src="/identity/made-beside-transparent.png" width="2172" height="724" alt="Made Beside"/></span></a><a className="header-call" href="/contact/">Let’s talk</a></header><nav ref={root} className={'bloom-menu'+(open?' is-open':'')} aria-label="Main navigation" onMouseEnter={()=>{if(matchMedia('(hover:hover)').matches)setOpen(true);}} onMouseLeave={()=>{if(!pinned&&!root.current.contains(document.activeElement))setOpen(false);}} onBlur={e=>{if(!root.current.contains(e.relatedTarget)){close();}}} onKeyDown={e=>{if(e.key==='Escape'){close();toggle.current.focus();}if(e.key==='ArrowDown'&&e.target===toggle.current){e.preventDefault();setOpen(true);requestAnimationFrame(()=>root.current.querySelector('a')?.focus());}}}>
 <button ref={toggle} className="bloom-toggle" aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="menu-destinations" onClick={()=>{if(pinned){close();}else{setOpen(true);setPinned(true);}}}><svg viewBox="0 0 24 24" aria-hidden="true"><path d={open?'M6 6 18 18M18 6 6 18':'M4 8h16M4 16h16'}/></svg></button>
 <div id="menu-destinations" className="menu-stack" inert={!open} aria-hidden={!open}>{links.map(([href,label],i)=><a className="bloom-item" key={href} href={href} aria-label={label} aria-current={location.pathname===href?'page':undefined} style={{'--item':i}}><span className="bloom-icon"><MenuIcon index={i}/></span><span className="bloom-label"><span>{label}</span></span></a>)}</div></nav></>;
}

