import fs from 'node:fs/promises';
const {header,footer}=JSON.parse(await fs.readFile('scripts/page-shell.json','utf8'));
const contact='<a href="mailto:Spencer@SpencerBMedia.com">Spencer@SpencerBMedia.com</a>';
const pages={
privacy:{title:'Privacy policy',intro:'Your note is a conversation starter. It is not a newsletter subscription.',sections:[
['Who is responsible',`Spencer B Media is based in Ontario, Canada. Spencer handles privacy questions and requests at ${contact}. This policy covers this website and inquiries made through it.`],
['What the form collects','The form asks for an email address and a message. Your name is optional. It also records a random submission reference, the time received, an expiry date and the version of the inquiry consent you accepted. Please do not include payment details, identity documents, health information, passwords or confidential project material. There are no attachment uploads.'],
['Why your information is used','Your details are used to receive and respond to your inquiry, discuss the work you requested and protect the form against misuse. The form does not enrol you in marketing. Your information is not sold, used for targeted advertising or added to a mailing list. Separate purposes require an appropriate legal basis and, where required, fresh consent.'],
['Service providers and international processing','The published website uses OpenAI Sites hosting and its infrastructure, including Cloudflare. Website inquiries are stored in a database restricted to the site operator; there is no public inquiry directory. Hosting, security and email providers may process information to deliver their services. Network requests can include your IP address, browser information and technical logs, even though the inquiry database does not store your IP address. Processing may occur outside Canada, including in the United States, where local laws can apply. Information may also be disclosed when required by law.'],
['Retention','Website inquiry records become eligible for deletion after 90 days. Cleanup runs when the website receives activity, at most once an hour; deletion can be delayed when the site is inactive. Copies in email, project records, provider backups or records required by law can have different retention periods. Information needed for a client engagement is handled for that engagement and retained only as needed for its purpose and legal obligations.'],
['Your choices and requests',`You can choose email instead of the form. Contact ${contact} to ask about access, correction, deletion or withdrawing consent. Reasonable identity verification may be needed, and legal requirements can limit deletion or access. Withdrawing permission to use necessary contact details may prevent a reply or continued service. Requests will be addressed within applicable legal timelines. You can also contact the <a href="https://www.priv.gc.ca/en/report-a-concern/">Office of the Privacy Commissioner of Canada</a>.`],
['Safeguards and cookies','Access restrictions, encrypted connections on the hosted site, limited form fields and input checks help protect information. No system can guarantee absolute security. The site application has no advertising pixels, visitor analytics, session replay, third-party content embeds or browser storage. See the <a href="/cookies/">cookie policy</a> for the distinction between this application and hosting services.'],
['Updates','Changes will be dated on this page. A policy update alone does not authorize a new use of previously collected information when additional consent is required.'] ]},
terms:{title:'Terms & conditions',intro:'A little clarity before we start a conversation.',sections:[
['About this website',`This website introduces the creative and marketing services offered under Spencer B Media in Ontario, Canada. Questions can be sent to ${contact}. The website is informational; sending an inquiry does not purchase services, reserve a production date or create a project agreement.`],
['Before work begins','Any paid engagement requires a separate agreement identifying the contracting party and setting out the scope, price, taxes, payment schedule, deliverables, revisions, approvals, expenses, cancellation terms and intellectual property arrangements. No payment is collected through this website. Do not assume a particular deliverable, turnaround time or licence is included until it is agreed in writing.'],
['Use of the site','Use the website lawfully. Do not submit material you are not entitled to share, send abusive or deceptive inquiries, attempt unauthorized access, interfere with the website or use the form for unsolicited bulk messages. Please send only information needed to discuss your inquiry.'],
['Creative material and rights','Website content and design may be protected by intellectual property rights held by Spencer B Media or the relevant rights holders. Visiting the site does not transfer those rights. Statutory exceptions remain available. Project ownership, third-party licences and permission to display client work must be settled in the relevant project agreement. The decorative correspondence on this website illustrates the creative approach; it is not evidence of a client engagement or client results.'],
['Information and outcomes','Service descriptions are general and may change. Marketing results depend on many factors and no specific audience growth, revenue, ranking or campaign outcome is promised. Reasonable care is taken with the site, but uninterrupted availability or error-free content is not guaranteed. This does not exclude any obligation, remedy or liability that applicable law does not allow to be excluded.'],
['Privacy and external links','The <a href="/privacy/">privacy policy</a> explains handling of inquiries. Links to other websites are provided for convenience; those sites have their own policies. Sending an inquiry does not authorize unrelated promotional emails.'],
['Applicable law and your rights','Ontario law and applicable federal Canadian law govern these website terms, subject to mandatory protections that apply where you live. Nothing here takes away non-waivable consumer rights, imposes mandatory arbitration, or prevents a complaint to an appropriate regulator. A separate signed project agreement governs the services it covers, subject to applicable law.'],
['Changes and contact',`The date below identifies this version. Changes do not retroactively alter a signed project agreement. Contact ${contact} about a concern or an error.`] ]},
cookies:{title:'Cookie policy',intro:'No advertising cookies. No visitor analytics added to this website.',sections:[
['What this application uses','The website application does not set cookies or use local storage, advertising pixels, session replay, browser fingerprinting or visitor analytics. Fonts and visual elements are served with the site. There are no embedded social feeds, maps or video players that load third-party tracking content. The motion preference exists only in the current page and resets when it is reloaded.'],
['Hosting and access services','Hosting and access providers may use necessary security, routing or sign-in technologies and maintain technical logs. A private site preview may require provider authentication. Those services are separate from optional tracking configured by Spencer B Media. This policy does not claim that the browser, hosting platform or other websites never use cookies.'],
['Why there is no optional-cookie banner','No optional tracking is configured in the site application, so it does not show an accept-all advertising or analytics banner. If optional tracking or third-party embeds are introduced, their purposes, providers and consent requirements must be reviewed before they are enabled. Where prior consent is required, those technologies must stay off until you choose them.'],
['Your controls',`Your browser can restrict or clear cookies. Restricting necessary provider cookies may affect sign-in or access. Questions about this website can be sent to ${contact}. See the <a href="/privacy/">privacy policy</a> for inquiry handling.`] ]},
refunds:{title:'Cancellations & refunds',intro:'No checkout. No payment just to say hello.',sections:[
['Website inquiries are free','This website does not take payments or automatically create a paid booking. Sending a contact form does not commit you to a purchase.'],
['Project terms come first','Before paid work begins, the project agreement should specify the payment schedule, deposits, expenses, cancellation or rescheduling conditions, completed-work charges and any refund arrangements. There is no blanket non-refundable deposit rule or universal cancellation fee established by this page.'],
['How to make a request',`Email ${contact} with your name, project reference and a brief explanation of your cancellation or refund request. Do not send card details or banking credentials. The request will be reviewed against the agreed terms, work completed, authorized commitments and applicable law. Any amount or timing will be confirmed in writing; this page does not promise a particular discretionary refund.`],
['Rights under law','Applicable statutory cancellation and refund rights take priority over any conflicting project term. Where a refund is legally required, it is not conditional on discretionary approval. Nothing on this page limits rights that cannot lawfully be waived.'] ]},
accessibility:{title:'Accessibility',intro:'The story should be available to everyone.',sections:[
['Using this website','The site is designed with semantic headings, visible keyboard focus, labelled fields and descriptive errors. The main information is available as text; decorative envelopes and paper effects are hidden from assistive technology. You do not need to drag objects or interact with an animation to read the services.'],
['Motion and reading','Use “Pause motion” at the bottom of the screen to stop decorative movement. The website also responds to your device’s reduced-motion preference. Service descriptions remain readable without animation or JavaScript. No audio plays automatically.'],
['Contact and alternatives',`If something is difficult to use, email ${contact}. Tell Spencer which page or task caused difficulty and your preferred way to receive the information. You do not need to disclose a diagnosis. An accessible alternative can be discussed with you.`],
['Ongoing improvement','Accessibility is an ongoing responsibility. These features are not a claim of independent certification or perfect compatibility with every browser and assistive technology. Reports of barriers help guide corrections.'] ]}
};
for(const [slug,page] of Object.entries(pages)){
await fs.mkdir('web/'+slug,{recursive:true});
await fs.writeFile(`web/${slug}/index.html`,`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${page.title} — Spencer B Media</title><meta name="description" content="${page.intro}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/style.css"><script src="/script.js" defer></script></head><body>${header}<main id="main" class="policy-main"><p class="small-label">Spencer B Media · Ontario, Canada</p><h1>${page.title}</h1><p class="policy-intro">${page.intro}</p><p class="policy-date">Last updated: September 18, 2026</p><div class="policy-content">${page.sections.map(([heading,text])=>`<section><h2>${heading}</h2><p>${text}</p></section>`).join('')}</div><a class="policy-back" href="/">← Back to Spencer’s note</a></main>${footer}</body></html>`);
}
await fs.writeFile('web/404.html',`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Address not found — Spencer B Media</title><link rel="stylesheet" href="/style.css"></head><body>${header}<main id="main" class="policy-main"><p class="small-label">Return to sender · 404</p><h1>A little<br>misdirected.</h1><p>This page isn’t at this address.</p><a href="/">Back to the homepage →</a></main>${footer}</body></html>`);
