import fs from 'node:fs/promises';
const old=await fs.readFile('web/index.html','utf8');
let form=old.match(/<form id="contact-form"[\s\S]*?<\/form>/)[0];
const footer=`<footer><a class="footer-name" href="/">Spencer B<span>Media & a personal touch.</span></a><div class="footer-bottom"><span>© 2026 Spencer B Media · Ontario, Canada</span><nav aria-label="Policies"><a href="/privacy/">Privacy</a><a href="/terms/">Terms</a><a href="/cookies/">Cookies</a><a href="/refunds/">Refunds</a><a href="/accessibility/">Accessibility</a></nav></div></footer><button class="motion-toggle" type="button" aria-pressed="false">Pause motion</button>`;
const header=`<a class="skip-link" href="#main">Skip to content</a><header><a class="wordmark" href="/" aria-label="Spencer B Media home">Spencer B<span>MEDIA</span></a><nav aria-label="Main"><a href="/#services">The contents</a><a href="/#contact">Write to me <span aria-hidden="true">↗</span></a></nav></header>`;
const head=(title,desc)=>`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} — Spencer B Media</title><meta name="description" content="${desc}"><meta name="theme-color" content="#eee8df"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><script src="/script.js" defer></script></head><body>`;
const envelope=`<div class="envelope" aria-hidden="true"><div class="envelope-back"></div><div class="envelope-flap"></div><div class="insert insert-one"><span>A thought, thoughtfully made.</span><b>Something<br>worth<br><em>feeling.</em></b><i>Film · photography · content</i></div><div class="insert insert-two"><span>From the desk of Spencer B</span><b>A little<br>different.<br><em>Very you.</em></b><i>Ideas · direction · brand</i></div><div class="insert insert-three"><span>Good things deserve to travel.</span><b>Out into<br>the <em>world.</em></b><i>Strategy · social · campaigns</i></div><div class="envelope-front"><span class="envelope-address">To: your next big idea<br>From: Spencer B Media</span><span class="wax-seal">S<span>B</span></span></div></div>`;
await fs.writeFile('web/index.html',head('A little more personal','Content creation, creative direction and marketing with Spencer B. Thoughtfully made in Ontario, Canada.')+header+`<main id="main"><section class="hero"><div class="hero-topline"><span>Independent spirit. Personal touch.</span><span>Ontario, Canada · Wherever your story goes.</span></div><div class="hero-title"><p class="handwritten">A note from Spencer.</p><h1>Good things<br>feel <em>personal.</em></h1><div class="hero-postage" aria-hidden="true"><span>PERSONALLY<br>CONSIDERED</span><b>SB</b><span>IDEAS ENCLOSED</span></div></div><div class="hero-bottom"><p>I make content. Shape ideas. Help brands find their people.<br>And I’d love to make something that feels like you.</p><a class="journey-link" href="#services">Let’s open this up <span aria-hidden="true">↓</span></a></div><div class="fold-line" aria-hidden="true"></div></section>
<section class="intro paper" id="about"><div class="letter-corner" aria-hidden="true"></div><p class="small-label reveal">From my desk to yours</p><h2 class="reveal">Dear people with<br><em>something to say,</em></h2><div class="intro-letter reveal"><p>I’m Spencer. I bring a creative eye and a thoughtful plan to the things your business puts into the world.</p><p>A film. A photograph. A campaign. Whatever the format, I want it to feel considered, connected and unmistakably yours.</p><p>No matter where we start, we start with a conversation.</p><span class="signature">Yours creatively,<strong>Spencer</strong></span></div></section>
<section class="mail-journey" id="services" aria-labelledby="contents-title"><div class="journey-heading"><p class="small-label">Enclosed, with care</p><h2 id="contents-title">A few things<br><em>I can bring.</em></h2><p>Keep scrolling. There’s a little more inside.</p></div><div class="journey-grid"><div class="mail-stage">${envelope}<p class="stage-caption" aria-hidden="true">GOOD IDEAS. NO POSTAGE REQUIRED.</p></div><div class="chapters"><article class="chapter" data-chapter="0"><span class="chapter-label">The making</span><h3>Something<br>you can <em>feel.</em></h3><p>Films, photographs and content that put a little more of you into every frame. From the first thought to the final edit.</p><p class="chapter-detail">Video & photography<br>Short-form content & editing</p></article><article class="chapter" data-chapter="1"><span class="chapter-label">The thinking</span><h3>A point<br>of <em>view.</em></h3><p>The idea behind the image. I help find the words, visual direction and creative thread that make everything belong together.</p><p class="chapter-detail">Creative direction & concepts<br>Brand storytelling & messaging</p></article><article class="chapter" data-chapter="2"><span class="chapter-label">The sending</span><h3>Made for<br><em>your people.</em></h3><p>Good work needs somewhere to go. I bring content and marketing together with a plan for how your story shows up.</p><p class="chapter-detail">Social content & campaign planning<br>Marketing strategy & ongoing refinement</p></article></div></div></section>
<section class="scrap-section"><div class="scrap paper reveal"><p class="small-label">A thought I keep coming back to</p><h2>People connect<br>with <em>people.</em></h2><p>So let’s leave a little of you in the work.</p><span class="pencil-line" aria-hidden="true"></span></div><span class="margin-note" aria-hidden="true">The important bit.<br>↖</span></section>
<section class="approach"><div class="approach-title reveal"><p class="small-label">A good back-and-forth</p><h2>Small beginnings.<br><em>Considered details.</em></h2></div><div class="approach-notes"><article class="reveal"><span>Tell me the unpolished version.</span><p>The half-formed idea, the thing you’re stuck on, the place you want to get to. We’ll give it a direction together.</p></article><article class="reveal"><span>Then we get into the making.</span><p>A clear brief, room for your feedback, and care in the details. I shape the work around what we’ve agreed to make.</p></article><article class="reveal"><span>And send it out with intention.</span><p>Ready for its channels and its people. For ongoing projects, we look at the response and decide what comes next.</p></article></div></section>
<section class="contact-section" id="contact"><div class="contact-heading reveal"><p class="small-label">Your turn</p><h2>Every good thing<br>starts with<br><em>“Hey, Spencer.”</em></h2><p>Tell me what you have in mind.<br>A rough idea is a lovely place to start.</p><a class="direct-email" href="mailto:Spencer@SpencerBMedia.com">Spencer@SpencerBMedia.com</a><p class="contact-location">Spencer B Media<br>Ontario, Canada</p><span class="signoff" aria-hidden="true">Speak soon,<br><b>Spencer</b></span></div>${form}</section></main>`+footer+'</body></html>');
await fs.writeFile('scripts/page-shell.json',JSON.stringify({header,footer}));
await fs.writeFile('web/favicon.svg',`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="32" fill="#563d59"/><text x="32" y="44" fill="#eee8df" text-anchor="middle" font-family="Georgia" font-size="39">S</text></svg>`);
