import fs from 'node:fs/promises';
const postal=await fs.readFile('web/index.html','utf8');
await fs.mkdir('web/iterations/postal',{recursive:true});let saved=postal;
for(const name of ['style.css','script.js','portfolio.css','portfolio.js','enhancements.css','enhancements.js','postal.css','postal.js']){await fs.copyFile('web/'+name,'web/iterations/postal/'+name);saved=saved.replaceAll('/'+name,'/iterations/postal/'+name);}await fs.writeFile('web/iterations/postal/index.html',saved);
let home=await fs.readFile('web/iterations/refined/index.html','utf8');home=home.replaceAll('/iterations/refined/','/').replace(/<script src="\/enhancements.js[^>]*><\/script>/,'');
const form=postal.match(/<form id="contact-form"[\s\S]*?<\/form>/)[0];home=home.replace(/<form id="contact-form"[\s\S]*?<\/form>/,form).replace('class="contact-section"','class="contact-section delivery-form"').replace('Got a good<br><span>feeling?</span>','Your next idea.<br><span>Send it my way.</span>').replace('Tell me the unpolished version.<br>A rough idea is a lovely place to start.','Tell me the unpolished version.<br>I’ll help it find its way into the world.').replace('There’s more in the package','Follow the delivery').replace('Orange film canister','Orange content canister');
home=home.replace('<a class="text-link" href="/portfolio/">Open the collection ↗</a>','<a class="round-action" href="/portfolio/">PORTFOLIO<br><span aria-hidden="true">↗</span></a>');
home=home.replace('<footer><a class="footer-name" href="/">spencer b.</a>','<footer><div class="footer-return"><a class="footer-name" href="/">spencer b.</a><div class="round-links"><a class="round-action" href="/portfolio/">PORTFOLIO<br><span aria-hidden="true">↗</span></a><a class="round-action" href="#contact">SAY HELLO<br><span aria-hidden="true">↗</span></a></div></div>');
home=home.replace('</head>','<link rel="stylesheet" href="/restored.css?v=1"></head>');home=home.replace(/\?v=[^" ]+/g,'?v=return1');await fs.writeFile('web/index.html',home);
for(const page of ['portfolio','studio','privacy','terms','cookies','refunds','accessibility']){const p='web/'+page+'/index.html';let s=await fs.readFile(p,'utf8');s=s.replace('class="postal-site"','').replace(/<link rel="stylesheet" href="\/postal.css[^>]*>/,'').replace(/<script src="\/enhancements.js[^>]*><\/script>/,'').replace(/\?v=[^" ]+/g,'?v=return1');await fs.writeFile(p,s);}
let js=await fs.readFile('web/script.js','utf8');js=js.replace("submit.disabled=true;submit.textContent='Sending your note…'","const submitLabel=submit.textContent;submit.disabled=true;submit.textContent='Sending your note…'").replace("submit.textContent='Send your note ↗'","submit.textContent=submitLabel");await fs.writeFile('web/script.js',js);
