const collection=document.querySelector('[data-collection]');
const studio=document.querySelector('#studio-tools');
let pieces=[],filter='all',currentPiece=0;
const el=(tag,text,cls)=>{const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node;};
async function api(url,options){const response=await fetch(url,options);let result;try{result=await response.json();}catch{throw Error('Could not connect. Please try again.');}if(!response.ok)throw Error(result.message||'Please try again.');return result;}
function media(piece,controls=false){const node=el(piece.kind==='video'?'video':'img');node.src=piece.src;if(piece.kind==='photo'){node.alt=piece.alt;node.loading='lazy';}else{node.controls=controls;node.preload='metadata';node.playsInline=true;node.setAttribute('aria-label',piece.title);if(piece.captions){const track=el('track');track.kind='captions';track.label='English';track.srclang='en';track.src=piece.captions;node.append(track);}}return node;}
let viewer;
function openPiece(index){currentPiece=index;if(!viewer){viewer=el('dialog',null,'work-viewer');document.body.append(viewer);viewer.addEventListener('close',()=>{viewer.querySelector('video')?.pause();});}viewer.replaceChildren();const p=pieces[index];const close=el('button','Close ×','viewer-close');close.onclick=()=>viewer.close();const heading=el('h2',p.title);heading.id='viewer-title';viewer.setAttribute('aria-labelledby','viewer-title');viewer.append(close,media(p,true),heading,el('p',p.description,'piece-description'));const navigation=el('div',null,'viewer-nav');for(const [label,step] of [[' Previous',-1],['Next ',1]]){const button=el('button',label);button.onclick=()=>{viewer.querySelector('video')?.pause();openPiece((currentPiece+step+pieces.length)%pieces.length);};navigation.append(button);}viewer.append(navigation);if(!viewer.open)viewer.showModal();close.focus();}
let canManage=false;
function renderCollection(){collection.replaceChildren();collection.classList.remove('has-open');const shown=pieces.filter(p=>filter==='all'||p.kind===filter);shown.forEach((p,i)=>{const card=el('article',null,'work-card mail-piece');card.style.setProperty('--tilt',[-3,2,-1,3][i%4]+'deg');const button=el('button',null,'piece-cover');button.setAttribute('aria-expanded','false');button.setAttribute('aria-label','Open '+p.title);button.append(media(p),el('span',p.kind==='video'?'Videography · Play ':'Photography · Open ','piece-kind'),el('h3',p.title));const details=el('div',null,'piece-inside');details.hidden=true;const close=el('button','Close ×','piece-close');const closePiece=()=>{details.querySelector('video')?.pause();details.hidden=true;details.replaceChildren();button.hidden=false;button.setAttribute('aria-expanded','false');card.classList.remove('is-open');collection.classList.remove('has-open');button.focus();};button.onclick=()=>{collection.querySelector('.piece-close')?.click();button.hidden=true;button.setAttribute('aria-expanded','true');details.hidden=false;card.classList.add('is-open');collection.classList.add('has-open');details.append(close,media(p,true),el('h3',p.title),el('p',p.description,'piece-description'));close.onclick=closePiece;close.focus({preventScroll:true});};card.addEventListener('keydown',event=>{if(event.key==='Escape'&&!details.hidden)closePiece();});card.append(button,details);collection.append(card);});const slots=collection.dataset.collection==='featured'?3:6;for(let i=shown.length;i<slots;i++){const kind=filter==='all'?(i%3===1?'video':'photo'):filter;const card=el('article',null,'work-card placeholder-piece '+kind);card.style.setProperty('--tilt',[-3,2,-1,3][i%4]+'deg');const frame=el('div',null,'placeholder-frame');frame.append(el('span','MEDIA PLACEHOLDER','placeholder-stamp'),el('strong',kind==='video'?'Press play.':'Picture this.'),el('span',kind==='video'?'A space for your next video.':'A space for your next photograph.'));card.append(frame,el('span',kind==='video'?'Videography':'Photography','piece-kind'));if(canManage){const add=el('a','Add your '+(kind==='video'?'video':'photo')+' ','add-media-link');add.href='/studio/?type='+kind+'#upload-work';card.append(add);}else card.append(el('p','New work will be added here.','placeholder-note'));collection.append(card);}}
if(collection){api('/api/portfolio').then(({items})=>{pieces=collection.dataset.collection==='featured'?items.filter(p=>p.featured).slice(0,3):items;if(collection.dataset.collection==='featured'&&!pieces.length)pieces=items.slice(0,3);renderCollection();}).catch(error=>{collection.replaceChildren(el('p',error.message));});document.querySelectorAll('[data-filter]').forEach(button=>button.onclick=()=>{filter=button.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderCollection();});}
function field(form,label,name,value,type='input'){const wrap=el('label',label);const input=el(type);input.name=name;input.value=value;wrap.append(input);form.append(wrap);return input;}
async function loadStudio(){const {items}=await api('/api/portfolio?all=1');const list=document.querySelector('#studio-list');list.replaceChildren();if(!items.length)list.append(el('p','Your first piece starts above. Drafts stay private until you publish them.'));for(const p of items){const form=el('form',null,'studio-edit');form.append(media(p,true));const title=field(form,'Title','title',p.title);title.required=true;title.maxLength=120;const description=field(form,'Description / transcript','description',p.description,'textarea');description.maxLength=2500;const alt=field(form,'Photo description','alt',p.alt);alt.maxLength=500;const order=field(form,'Display order (lowest first)','order',p.order);order.type='number';order.min=-10000;order.max=10000;const status=field(form,'Visibility','status','','select');for(const value of ['draft','published','archived']){const option=el('option',value[0].toUpperCase()+value.slice(1));option.value=value;status.append(option);}status.value=p.status;const feature=field(form,'Feature on homepage','featured','');feature.type='checkbox';feature.checked=p.featured;const save=el('button','Save changes','button');const note=el('p');note.setAttribute('role','status');form.append(save,note);form.onsubmit=async event=>{event.preventDefault();save.disabled=true;note.textContent='Saving…';try{await api('/api/portfolio/'+p.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:title.value,description:description.value,alt:alt.value,order:Number(order.value),status:status.value,featured:feature.checked})});note.textContent='Saved. '+(status.value==='published'?'This piece is live.':'This piece is private.');}catch(error){note.textContent=error.message;}finally{save.disabled=false;}};list.append(form);}}
if(collection||studio)api('/api/portfolio/session').then(async session=>{canManage=session.canManage;document.querySelectorAll('.owner-link').forEach(n=>n.hidden=!session.canManage);if(collection)renderCollection();if(!studio)return;const access=document.querySelector('#studio-access');if(!session.canManage){access.textContent='This studio is reserved for the site owner. Open this site while signed in to your owner account.';return;}access.textContent='Owner access · drafts are private';studio.hidden=false;await loadStudio();}).catch(error=>{if(studio)document.querySelector('#studio-access').textContent=error.message;});
const uploadForm=document.querySelector('#upload-work');
if(uploadForm){
 const input=uploadForm.elements.file,preview=document.querySelector('#upload-preview'),status=uploadForm.querySelector('.upload-status'),drop=document.querySelector('#media-drop'),progress=document.querySelector('#upload-progress');let previewURL=null,busy=false;
 function clearPreview(){preview.querySelector('video')?.pause();if(previewURL)URL.revokeObjectURL(previewURL);previewURL=null;preview.replaceChildren();preview.hidden=true;}
 function choose(){clearPreview();const file=input.files[0];if(!file)return;status.textContent='';if(file.size>20*1024*1024){status.textContent='This file is over 20 MB. Choose a smaller web-ready copy.';input.value='';return;}const video=file.type.startsWith('video/');if(!['image/jpeg','image/png','image/webp','video/mp4','video/webm'].includes(file.type)){status.textContent='Choose JPG, PNG, WebP, MP4 or WebM.';input.value='';return;}previewURL=URL.createObjectURL(file);const node=el(video?'video':'img');node.src=previewURL;if(video){node.controls=true;node.preload='metadata';node.playsInline=true;}else node.alt='Preview of the photo you selected';preview.append(node,el('p',file.name+' · '+(file.size/1024/1024).toFixed(1)+' MB'));preview.hidden=false;uploadForm.querySelectorAll('[data-video-field]').forEach(n=>n.hidden=!video);uploadForm.querySelector('[data-photo-field]').hidden=video;uploadForm.elements.alt.required=!video;uploadForm.elements.description.required=video;uploadForm.elements.captions.required=video&&uploadForm.elements.hasSpeech.value==='yes';if(!uploadForm.elements.title.value)uploadForm.elements.title.value=file.name.replace(/\.[^.]+$/,'').replace(/[_-]+/g,' ').slice(0,120);}
 input.addEventListener('change',choose);uploadForm.elements.hasSpeech.addEventListener('change',()=>{uploadForm.elements.captions.required=uploadForm.elements.hasSpeech.value==='yes'&&input.files[0]?.type.startsWith('video/');});
 for(const event of ['dragenter','dragover'])drop.addEventListener(event,e=>{e.preventDefault();if(!busy)drop.classList.add('drag-over');});for(const event of ['dragleave','drop'])drop.addEventListener(event,e=>{e.preventDefault();drop.classList.remove('drag-over');});drop.addEventListener('drop',e=>{if(busy)return;if(e.dataTransfer.files.length!==1){status.textContent='Add one piece at a time so each can have its own title and description.';return;}input.files=e.dataTransfer.files;choose();});
 function upload(data){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST','/api/portfolio');xhr.upload.onprogress=event=>{if(event.lengthComputable){progress.value=Math.round(event.loaded/event.total*100);status.textContent=progress.value===100?'Upload received. Saving your piece…':'Uploading… '+progress.value+'%';}};xhr.onload=()=>{let result;try{result=JSON.parse(xhr.responseText);}catch{return reject(Error('Could not confirm the upload. Check your drafts before trying again.'));}if(xhr.status>=200&&xhr.status<300)resolve(result);else reject(Error(result.message||'Upload failed. Please try again.'));};xhr.onerror=()=>reject(Error('Connection lost. Check your drafts before uploading again; your file selection is still here.'));xhr.send(data);});}
 uploadForm.addEventListener('submit',async event=>{event.preventDefault();if(busy)return;const data=new FormData(uploadForm),publish=event.submitter?.value==='publish',featured=uploadForm.elements.featured.checked;let saved=false;busy=true;const controls=[...uploadForm.querySelectorAll('input,textarea,select,button')];controls.forEach(n=>n.disabled=true);progress.hidden=false;progress.value=0;status.textContent='Uploading…';try{const {item}=await upload(data);saved=true;uploadForm.reset();clearPreview();uploadForm.querySelectorAll('[data-video-field]').forEach(n=>n.hidden=true);uploadForm.querySelector('[data-photo-field]').hidden=false;uploadForm.elements.captions.required=false;uploadForm.elements.description.required=false;uploadForm.elements.alt.required=false;if(publish||featured)await api('/api/portfolio/'+item.id,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:item.title,description:item.description,alt:item.alt,status:publish?'published':'draft',featured,order:0})});status.textContent=publish?'Published! Open your portfolio to see it.':'Draft saved. Only you can see it until you publish.';await loadStudio();}catch(error){status.textContent=saved?'Your file is saved. The final update could not be confirmed; check its visibility in Your collection below.':error.message;if(saved)await loadStudio().catch(()=>{});}finally{busy=false;controls.forEach(n=>n.disabled=false);progress.hidden=true;}});
 window.addEventListener('pagehide',clearPreview);
}
