const postalScene=document.querySelector('.envelope-scene');
if(postalScene){
 document.body.classList.add('postal-ready');
 const stops=[...document.querySelectorAll('.route-step')],objects=[...document.querySelectorAll('.route-object')],names=['Discovery call','Concept & direction','Design & creation','Build & production','Launch & handoff'];
 const tracker=document.querySelector('.delivery-tracker'),state=document.querySelector('.tracker-state'),manifest=document.querySelector('[data-stop-name]'),visual=document.querySelector('.route-visual');let queued=false,lastStop=-1,lastState='';
 const paused=()=>document.body.classList.contains('motion-paused')||document.hidden;
 if(!paused()){postalScene.classList.add('opening');setTimeout(()=>postalScene.classList.remove('opening'),1750);}
 function renderPostal(){queued=false;const progress=Math.max(0,Math.min(1,scrollY/Math.max(1,document.documentElement.scrollHeight-innerHeight)));tracker.style.setProperty('--delivery-progress',progress);tracker.setAttribute('aria-valuenow',String(Math.round(progress*100)));const nextState=progress<.14?'Processing':progress<.92?'In transit':'Delivered';if(lastState!==nextState){state.textContent=nextState;lastState=nextState;}
  const anchor=innerHeight*(innerWidth<=700?.65:.53);let nearest=0,distance=Infinity;stops.forEach((stop,i)=>{const r=stop.getBoundingClientRect(),d=Math.abs(r.top+r.height*.5-anchor);if(d<distance){distance=d;nearest=i;}});if(lastStop!==nearest){objects.forEach((object,i)=>object.classList.toggle('active',i===nearest));manifest.textContent=names[nearest];visual.style.setProperty('--route-progress',(nearest+1)/5);lastStop=nearest;}
  document.querySelectorAll('[data-collect]').forEach((stamp,i)=>{if(i<=nearest)stamp.classList.add('received');});
  if(paused())return;const r=postalScene.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){const p=Math.max(0,Math.min(1,-r.top/r.height));postalScene.style.setProperty('--letter-y',(-p*90)+'px');postalScene.style.setProperty('--flap-angle',(p*8)+'deg');}
  const peel=document.querySelector('.peel-transition'),pr=peel.getBoundingClientRect();if(pr.top<innerHeight&&pr.bottom>0){const p=Math.max(0,Math.min(1,(innerHeight-pr.top)/(innerHeight+pr.height)));peel.style.setProperty('--peel-x',(p*70)+'px');peel.style.setProperty('--peel-rotate',(p*-28)+'deg');peel.style.setProperty('--tape-peel',(p*18)+'deg');}
  const memo=document.querySelector('.memo-illustration'),mr=memo.getBoundingClientRect();if(mr.top<innerHeight&&mr.bottom>0)memo.style.setProperty('--memo-drift',((innerHeight-mr.top)/(innerHeight+mr.height)*-45)+'px');
 }
 function schedulePostal(){if(!queued){queued=true;requestAnimationFrame(renderPostal);}}
 addEventListener('scroll',schedulePostal,{passive:true});addEventListener('resize',schedulePostal);document.querySelector('.motion-toggle')?.addEventListener('click',schedulePostal);renderPostal();
 const collectObserver=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('collected');collectObserver.unobserve(entry.target);}}),{threshold:.4});document.querySelectorAll('.collected-mark').forEach(mark=>{mark.parentElement.classList.add('collect-ready');collectObserver.observe(mark);});
 document.querySelectorAll('.seal-trigger,.send-button').forEach(button=>button.addEventListener('click',()=>{if(paused())return;button.classList.remove('seal-pop');requestAnimationFrame(()=>button.classList.add('seal-pop'));const seal=document.createElement('img');seal.src='/postal/wax-seal.webp';seal.alt='';seal.className='wax-impression';seal.setAttribute('aria-hidden','true');const bounds=button.getBoundingClientRect();seal.style.left=Math.min(innerWidth-80,Math.max(0,bounds.right-45))+'px';seal.style.top=Math.min(innerHeight-85,Math.max(0,bounds.top-20))+'px';document.body.append(seal);setTimeout(()=>seal.remove(),900);}));
}
const objectArrivals=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('arrived');objectArrivals.unobserve(entry.target);}}),{threshold:.2});document.querySelectorAll('.route-step').forEach(step=>objectArrivals.observe(step));
